MichelGlazenborg/Parking_Garage

src/Main.java

Restoring base

---

src/Main.java

Added a print which prints: "This is a Test."

Added a print

---

src/Main.java

line removed

---

src/Main.java

testing-stuff

---

src/Controller/Controller.java
src/Models/Simulator.java
src/View/Parkeergarage.fxml

Buttons are now disabled during simulations

---

src/Models/PassHolderSpace.java
src/Models/Reservation.java
src/Models/Simulator.java
src/Models/SimulatorView.java

Hoewel het meestal niet een heel goed idee is om properties public te maken, is het in dit geval wel de makkelijkste en snelste oplossing. We kunnen de setter niet statisch maken omdat er wordt verwacht dat er een methode in de klasse staat met als header 'public Color getColor()'. Een tweede (en statische) getter aanmaken lukt ook niet (en is sowieso een beetje raar :P).

De color constant kan beter public zijn

---

src/Controller/Controller.java
src/Models/SimulatorView.java
src/View/Parkeergarage.fxml

Version 1 of makePassHolderRows

Version 1 of makePassHolderRows

---

src/Controller/Controller.java
src/Models/SimulatorView.java
src/View/Parkeergarage.fxml

Change makePassHolderRows to makePassHolderSpots.

Change makePassHolderRows to makePassHolderSpots.

---

src/Controller/Controller.java
src/Models/Simulator.java
src/View/Parkeergarage.fxml

Added setPrice method.

---

src/Main.java
src/controller/Controller.java
src/controller/Popup.java
src/models/AdHocCar.java
src/models/Car.java
src/models/CarQueue.java
src/models/CarWithReservedSpot.java
src/models/Location.java
src/models/ParkingPassCar.java
src/models/PassHolderSpace.java
src/models/Payment.java
src/models/Reservation.java
src/models/Simulator.java
src/models/SimulatorView.java
src/models/StatsData.java
src/models/StatsPie.java
src/style.css
src/view/Parkeergarage.fxml
src/view/StatsGraph.java

Changed package names to lowercase & added some color.

Changed package names to lowercase & added some color.

---

src/Models/SimulatorView.java
src/Models/StatsPie.java
src/style.css

! Simulator freezing up

---

src/models/SimulatorView.java

This is probably a little faster

---

src/style.css

Changed some color + implemented hover.

Changed some color + implemented hover.

---

src/controller/Controller.java
src/models/PassHolderSpace.java
src/models/Reservation.java
src/view/ParkingGarage.fxml

Fixed typos + Removed some unnecessary code.

Fixed typos + Removed some unnecessary code.

---

src/controller/Controller.java

controller.java javadocs opgeruimd

Javadoc cleanup

---

src/models/SimulatorView.java

Fixed issue #95

---

src/models/Car.java
src/models/PassHolderSpace.java

Black spots are now INFINITE!!!!!

Black spots are now INFINITE!!!!!

---

src/style.css

Edited css file to be more "viewable"

Edited css file to be more "viewable"

---

src/controller/Controller.java
src/models/SimulatorView.java

makePassHolderSpots now resets everything.

makePassHolderSpots now resets everything.

---

src/controller/Controller.java

extra timeline

---

src/controller/Controller.java

! Error popup is displayed twice upon invalid integer input

---

src/controller/Controller.java
src/view/ParkingGarage.fxml

Changed submit to tickFor.

---

src/models/OccupationChart.java

Fixed some typos

---

src/view/ParkingGarage.fxml

update() aangemaakt voor alle updates die de extra timeline moet doen.
En de views kunnen aan en uit worden gezet

Update, views

---

src/controller/Controller.java

controller met al die mangagedingusses

Controller ??

---

src/controller/Controller.java
src/controller/TimeInputPopupController.java
src/main/Main.java
src/models/AdHocCar.java
src/models/Car.java
src/models/CarWithReservedSpot.java
src/models/Garage.java
src/models/Location.java
src/models/OccupationChart.java
src/models/OccupationChartData.java
src/models/ParkingPassCar.java
src/models/PassHolderSpace.java
src/models/Payment.java
src/models/Popup.java
src/models/Reservation.java
src/models/Simulator.java
src/models/TimeInputPopup.java
src/view/DailyCarsChartView.java
src/view/GarageView.java
src/view/OccupationChartView.java
src/view/ParkingGarage.fxml

The Controller and Simulator classes still don't fully comply with the MVC design pattern, but I'm not sure how long it would take. We might be better off leaving things as they are, that way we could focus on catching and fixing bugs.
I also did some cleaning up; moving getters and setters to the bottom of the class, adding whitespace and new lines, etc. It's not completely done yet, but it shouldn't cause any major problems.

File restructuring (please read)

---

src/controller/Controller.java

ResetTime now apply's instantly

ResetTime now apply's instantly

---

src/controller/Controller.java

speed control

---

src/controller/Controller.java
src/models/Garage.java

Max rows are now 6.
